/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CirclePackingFlat: typeof import('./src/components/CirclePackingFlat.vue')['default']
    CirclePackingSettings: typeof import('./src/components/CirclePackingSettings.vue')['default']
    ConditionNode: typeof import('./src/components/ConditionNode.vue')['default']
    ConnectionEditor: typeof import('./src/components/ConnectionEditor.vue')['default']
    EditableEventNode: typeof import('./src/components/EditableEventNode.vue')['default']
    EditorSettingsDialog: typeof import('./src/components/EditorSettingsDialog.vue')['default']
    EssentialLink: typeof import('./src/components/EssentialLink.vue')['default']
    EventBindingsDisplay: typeof import('./src/components/EventBindingsDisplay.vue')['default']
    ExampleComponent: typeof import('./src/components/ExampleComponent.vue')['default']
    ExplorerTree: typeof import('./src/components/ExplorerTree.vue')['default']
    LoopbackEdge: typeof import('./src/components/LoopbackEdge.vue')['default']
    NodeEditDialog: typeof import('./src/components/NodeEditDialog.vue')['default']
    NodeHoverTooltip: typeof import('./src/components/NodeHoverTooltip.vue')['default']
    RelationGraphToolBar: typeof import('./src/components/RelationGraphToolBar.vue')['default']
    RelationshipCard: typeof import('./src/components/RelationshipCard.vue')['default']
    RoleCard: typeof import('./src/components/RoleCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TimelineEventEditor: typeof import('./src/components/TimelineEventEditor.vue')['default']
    TimelineRenderSettings: typeof import('./src/components/TimelineRenderSettings.vue')['default']
    TimelineView: typeof import('./src/components/TimelineView.vue')['default']
    TimeSeriesChart: typeof import('./src/components/TimeSeriesChart.vue')['default']
    UniversalEditor: typeof import('./src/components/UniversalEditor.vue')['default']
    UniversalEditorModal: typeof import('./src/components/UniversalEditorModal.vue')['default']
  }
}
