[workspace]
authors = ["AndreaFrederica <andreafrederica@outlook.com>"]
channels = ["conda-forge"]
name = "andrea-novel-helper"
platforms = ["win-64"]
version = "0.1.0"

[tasks]
server = { cmd = [
    "python",
    "static_server.py",
    "--dir",
    "./packages/webview/dist/spa",
    "--port",
    "5173",
] }

build = { cmd = ["npm", "run", "compile"] }

build_web = { cmd = ["npm", "run", "build:webview"] }

build_all = { depends-on = ["build_web", "build"] }

web_dev = { cmd = ["npm", "run", "dev:webview"] }

publish = { cmd = ["npx", "vsce", "publish"] }

publish_ovsx = { cmd = ["npx", "ovsx", "publish"] }

publish_all = { depends-on = ["publish", "publish_ovsx"] }


[dependencies]
python = ">=3.13.5,<3.14"
